# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
config.vm.box = "debian/buster64"
  config.vm.network "public_network", ip: "192.168.1.7"		
  config.vm.provider "virtualbox" do |vb|
  config.vm.synced_folder "page", "/vagrant"
vb.memory = "2048"
   config.vm.provision "ansible", run: "always" do |ansible|
	ansible.playbook = "holaMundo.yml"
end
end
end
