Vagrant.configure("2") do |config|
  config.vm.box = "elementary"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |vm|
        vm.gui = true
        vm.memory = "1024"
end
end
