# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "linuxMint"
  config.vm.network "public_network", ip: "192.168.1.6"
  config.vm.provider "virtualbox" do |vb|
   vb.gui = true
   vb.memory = "2048"
end
end
