Vagrant.configure("2") do |config|
  config.vm.box = "xp"
  config.vm.network "private_network", type: "dhcp"
  config.vm.synced_folder "./WinQSB/", "/vagrant"
  config.vm.guest = :windows
  config.vm.provider "virtualbox" do |vm|
	vm.gui = true
        vm.memory = "2048"

end
end
